from .model import OutputMode as OutputMode, Rect as Rect
from _typeshed import Incomplete

class _BaseReply:
    ipc_data: Incomplete
    def __init__(self, data) -> None: ...

class CommandReply(_BaseReply): ...
class WorkspaceReply(_BaseReply): ...
class OutputReply(_BaseReply): ...

class BarConfigGaps:
    left: Incomplete
    right: Incomplete
    top: Incomplete
    bottom: Incomplete
    def __init__(self, data) -> None: ...

class BarConfigReply(_BaseReply): ...
class VersionReply(_BaseReply): ...
class ConfigReply(_BaseReply): ...
class TickReply(_BaseReply): ...
class InputReply(_BaseReply): ...
class SeatReply(_BaseReply): ...
